language: android

android:
  components:
  - build-tools-23.0.1
  - android-23
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-android-support

jdk:
- oraclejdk8

branches:
  only:
  - master

before_install:
- openssl aes-256-cbc -K $encrypted_3366a34600b0_key -iv $encrypted_3366a34600b0_iv -in SecretStuff.java.enc -out app/src/main/java/com/chromium/fontinstaller/SecretStuff.java -d
