language: android
jdk: oraclejdk8
android:
  components:
    # The BuildTools version used by your project
    - build-tools-23.0.1

    # The SDK version used to compile your project
    - android-23
env:
  matrix:
  - ANDROID_TARGET=android-23  ANDROID_ABI=armeabi-v7a
before_install:
  - echo no | android create avd --force -n test -t android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window &
before_script:
  - ./ci/wait_for_emulator
  - adb shell input keyevent 82 &