language: android
jdk:
  - oraclejdk8
  
android:
  components:
    - build-tools-23.0.1
    - android-23
    - extra-android-m2repository
    - extra-google-m2repository
    - extra-google-google_play_services

branches:
  only:
    - master

before_install:
  - "echo $GRADLE_OPTS"
  - openssl aes-256-cbc -K $encrypted_3366a34600b0_key -iv $encrypted_3366a34600b0_iv -in SecretStuff.java.enc -out app/src/main/java/com/chromium/fontinstaller/SecretStuff.java -d
